### ISSUE TITLE
rename project to `dockercursion`

### ISSUE THREAD

**Issue by marzocchi** [aspacca/dockerecursion#2]
sounds way better!

**Comment by marzocchi** [comment]
dropping vowels is also good for branding ([source](https://money.howstuffworks.com/flickr-tumblr-scribd-why-dropping-vowels-brand-names-is-popular.htm))

**Comment by felipebool** [comment]
that's a good way to think, but, maybe, both names are just bad.

**Comment by marzocchi** [comment]
that's a very negative attitude!
